### ISSUE TITLE
Move this repo upstream

### ISSUE THREAD

**Issue by pierreozoux** [kube-object-storage/lib-bucket-provisioner#186]
Hi,

I'm trying to work on this [KEP](https://github.com/kubernetes/enhancements/issues/706), and this library is a really good example for it.

Do you have a better idea than me on how to move this upstream?

I think it would be amazing to show the community this example, so that the community starts to reproduce more this pattern of having a definition and an implementation separated.

**Comment by jeffvance** [comment]
Question: what do you mean by _upstream_? Our original goal was for this repo to live under the kubernetes umbrella but sig-storage was not in favor of that at the time. Now we have a [KEP](https://github.com/kubernetes/enhancements/pull/1383) which is being reviewed by sig-storage with the hopeful outcome that:
.  this repo is hosted in k8s
.  the API will be implemented following the CSI spec instead of using a library.

@copejon @guymguym @nimrod-becker Thoughts?

**Comment by pierreozoux** [comment]
I didn't know about this plan, and this is perfect.

Thanks for your answer and the nice work you are all doing!
